[general]
import = [
    "~/.config/alacritty/themes/themes/github_dark_tritanopia.toml"
]


[font]
size = 10 

[font.normal]
family ="Hack Nerd Font"
style="Bold"



[font.bold]
family ="Hack Nerd Font"
style="Bold"

[font.italic]
family ="Hack Nerd Font"
style="Bold"
